theme= "catppuccin_mocha"

[editor]
# line-number = "relative"
bufferline = "multiple"
color-modes= true
cursorline = true
mouse = false
gutters = ["diff","diagnostics", "line-numbers", "spacer"]
text-width = 80
auto-format = true
auto-save = true
auto-completion = true


[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"


[editor.statusline]
left = ["mode", "spinner", "version-control", "file-modification-indicator", "read-only-indicator"]
center = ["file-name"]
right = ["diagnostics","register","selections", "position", "file-encoding", "file-line-ending", "file-type"]
separator = "|"
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"

[editor.lsp]
enable = true
display-messages = true
auto-signature-help = true

[editor.file-picker]
hidden = false

[editor.soft-wrap]
enable = true
max-wrap = 25
max-indent-retain = 80
wrap-indicator = ""

[editor.indent-guides]
render = true
character = "┊"
