# [language.auto-pairs]
# '(' = ')'
# '{' = '}'
# '[' = ']'
# '"' = '"'
# '`' = '`'


[[language]]
name = "go"
indent = {tab-width = 2, unit = " "}
file-types = ["go", "gotmpl", "gomod", "gosum", "tmpl"]

[language.auto-pairs]
'(' = ')'
'{' = '}'
'[' = ']'
'"' = '"'
'`' = '`'


# [language-server.gols]
# command = "gols"

# [language-server.gols.config]
# inlayHints.bindingModeHints = false
# inlayHints.closingBraceHints.minLines = 10
# inlayHints.closureReturnTypeHints.enable = "with_block"
# inlayHints.discriminantHints.enable = "fieldless"
# inlayHints.lifetimeElisionHints.enable = "skip_trivial"
# inlayHints.typeHints.hideClosureInitialization = false

 
[[language]]
name = "gleam"

[language-server]
biome = {command = "biome", args = ["lsp-proxy"]}
emmet-ls = {command = "emmet-ls", args = ["--stdio"]}

[language-server.eslint]
command = "vscode-eslint-language-server"
args= [ "--stdio"]

[language-server.eslint.config]
codeActionsOnSave = {mode = "all", "source.fixAll.eslint" = true}
format = { enable = true }
nodePath = ""
quiet = false
rulesCustomizations = []
run = "onType"
validate = "on"
experimental = {}
problems = { shortenToSingleLine = false }


[language-server.eslint.config.codeAction]
disableRuleComment = {enable = true, location = "separateLine"}
showDocumentations = { enable = true }

[language-server.vscode-json-language-server.config]
json={validate={enable=true},format={enable=true}}
provideFormatter = true

[language-server.vscode-css-language-server.config]
css ={validate = {enable=true}}
scss ={validate ={enable= true}}
less = {validate = {enable = true}}
provideFormatter = true

[[language]]
name = "javascript"
language-servers = [{ name ="typescript-language-server", except-features = ["format"] }, "biome", "emmet-ls",  "tailwindcss-ls","eslint"]
formatter = {command ="dprint", args = ["fmt", "--stdin", "typescript"]}
auto-format = true

[[language]]
name = "typescript"
language-servers = [{ name ="typescript-language-server", except-features = ["format"] }, "biome", "emmet-ls","tailwindcss-ls", "eslint"]
formatter= {command = "dprint", args= ["fmt", "--stdin", "typescript"]}
auto-format = true

[[language]]
name ="scss"

[[language]]
name = "css"
language-servers = ["vscode-css-language-server", "emmet-ls"]
formatter = {command = "prettier", args = ["--parser", "css"]}
auto-format = true

[[language]]
name ="html"
file-types = ["html", "htm", "tmpl", "gotmpl"]
language-servers = ["vscode-html-language-server", "tailwindcss-ls","emmet-ls"]
formatter = { command ="prettier", args = ["--parser", "html"] }
auto-format = true

[[language]]
name= "jsx"
language-servers = [{ name ="typescript-language-server", except-features = ["format"] }, "biome", "emmet-ls", "tailwindcss-ls","eslint" ]
formatter = {command= "dprint", args = ["fmt", "--stdin", "jsx"]}
auto-format = true

[[language]]
name= "tsx"
language-servers = [{ name ="typescript-language-server", except-features = ["format"] }, "biome", "emmet-ls", "tailwindcss-ls", "eslint"]
formatter = { command = "dprint", args = ["fmt", "--stdin", "tsx"]}
auto-format = true

[[language]]
name = "dockerfile"
file-types = ["Dockerfile", "dockerfile"]


[[language]]
name = "json"
formatter = {command ="dprint", args =["fmt", "--stdin", "json"]}

[[language]]
name ="toml"


[[language]]
name = "vue"

[[language]]
name = "svelte"


[[language]]
name = "git-commit"
language-servers = [ "scls"]
